### model
model_name_or_path: ./temp/results/sft/qwen/full-task2_prompt0_train

### method
stage: sft
do_predict: true
finetuning_type: full

### dataset
dataset_dir: ./data/dataset
dataset: manual_prompt0
template: qwen
cutoff_len: 512
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./temp/results/predict/qwen/full-task2_prompt0_train-manual
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 1
predict_with_generate: true
