### model
model_name_or_path: ./temp/models/Qwen1.5-7B

### method
stage: sft
do_train: true
finetuning_type: full

### ddp
ddp_timeout: 180000000
deepspeed: ./config/ds_z3_config.json

### dataset
dataset_dir: ./data/dataset
dataset: task2_prompt0_train
template: qwen
cutoff_len: 512
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./temp/results/sft/qwen/full-task2_prompt0_train
logging_steps: 10
load_best_model_at_end: true  # load the best model when training ends
save_total_limit: 1           # only keep one checkpoint(if not the best) in the output directory
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 0.0001
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500
